import { createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { PhilyraGeneratedModule, PhilyraGeneratedSharedModule } from './generated/module';
import { PhilyraAstNodeDescriptionProvider } from './index/PhilyraAstNodeDescriptionProvider';
import { PhilyraNameProvider } from './references/PhilyraNameProvider';
import { PhilyraScopeComputation } from './references/PhilyraScopeComputation';
import { PhilyraScopeProvider } from './references/PhilyraScopeProvider';
import { PhilyraValidator, PhilyraValidationRegistry } from './validation/PhilyraValidator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type PhilyraAddedServices = {
  validation: {
    PhilyraValidator: PhilyraValidator
  }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type PhilyraServices = LangiumServices & PhilyraAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const PhilyraModule: Module<PhilyraServices, PartialLangiumServices & PhilyraAddedServices> = {
  validation: {
    ValidationRegistry: (injector) => new PhilyraValidationRegistry(injector),
    PhilyraValidator: () => new PhilyraValidator()
  },
  index: {
    AstNodeDescriptionProvider: (injector) => new PhilyraAstNodeDescriptionProvider(injector)
  },
  references: {
    NameProvider: () => new PhilyraNameProvider(),
    ScopeComputation: (injector) => new PhilyraScopeComputation(injector),
    ScopeProvider: (injector) => new PhilyraScopeProvider(injector)
  }
};

/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createPhilyraServices(context?: DefaultSharedModuleContext): {
  shared: LangiumSharedServices,
  philyra: PhilyraServices
} {
  const shared = inject(
    createDefaultSharedModule(context),
    PhilyraGeneratedSharedModule
  );
  const philyra = inject(
    createDefaultModule({ shared }),
    PhilyraGeneratedModule,
    PhilyraModule
  );
  shared.ServiceRegistry.register(philyra);
  return { shared, philyra };
}
